name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dave33m
          template: classic

          # Output file settings
          filename: github-metrics.svg
          output_action: commit

          # Force commit to your default branch
          committer_branch: main

          # Base sections
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 1%

          plugin_followup: yes
          plugin_stars: yes

          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 12

          plugin_lines: yes

          # Disable failing plugin
          plugin_achievements: no

          # Fix for stuck yellow runs
          clean_workflows: true
